function Gsparse = Dense2SparseGraph(Gdense,nhood)
% converts a dense graph to a symmetric sparse graph
% Gdense: dense lattice graph
% nhood: lattice neighborhood, as generated by mknhood.m

Gsparse = Dense2SparseGraphAssym(Gdense,nhood);

% symmetrize the graph
Gsparse = Gsparse + Gsparse';
